[package]
name = "ovhctl"
version = "0.1.0"
authors = ["Florentin Dubois <florentin.dubois@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.41"
bytes = "^0.5.6"
config = "^0.10.1"
chrono = "^0.4.19"
futures = "^0.3.6"
hyper = "^0.13.8"
hyper-tls = "^0.4.3"
ipnetwork = "^0.17.0"
paw = "^1.0.0"
pbr = "^1.0.3"
prettytable-rs = "^0.8.0"
rust-crypto = "^0.2.36"
serde = { version = "^1.0.116", features = ["derive"] }
serde_json = "^1.0.59"
serde_yaml = "^0.8.13"
slog = { version = "^2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "^2.5.0"
slog-term = "^2.6.0"
slog-scope = "^4.3.0"
structopt = { version = "^0.3.20", features = ["paw"] }
tokio = { version = "^0.2.22", features = ["full"] }
