[package]
name = "ovhctl"
version = "0.1.0"
authors = ["Florentin Dubois <florentin.dubois@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.42"
bytes = "^1.0.0"
config = "^0.10.1"
chrono = "^0.4.19"
futures = "^0.3.8"
hyper = { version = "^0.14.2", features = ["full"] }
hyper-tls = "^0.5.0"
ipnetwork = "^0.17.0"
paw = "^1.0.0"
pbr = "^1.0.3"
prettytable-rs = "^0.8.0"
rust-crypto = "^0.2.36"
serde = { version = "^1.0.118", features = ["derive"] }
serde_json = "^1.0.61"
serde_yaml = "^0.8.14"
slog = { version = "^2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "^2.5.0"
slog-term = "^2.6.0"
slog-scope = "^4.3.0"
structopt = { version = "^0.3.21", features = ["paw"] }
tokio = { version = "^1.0.1", features = ["full"] }
